{% set version = "0.1.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ggpointless
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggpointless_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggpointless/ggpointless_{{ version }}.tar.gz
  sha256: 496dee3fcc02b2088d0faa9b0245fbf3dc5cf7c902fffe6ea25e0fa6982cede3

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggplot2 >=3.3.0
  run:
    - r-base
    - r-ggplot2 >=3.3.0

test:
  commands:
    - $R -e "library('ggpointless')"           # [not win]
    - "\"%R%\" -e \"library('ggpointless')\""  # [win]

about:
  home: https://flrd.github.io/ggpointless/, https://github.com/flrd/ggpointless
  license: MIT
  summary: Add minimal emphasis to your plots. 'ggpointless' is a small extension of the 'ggplot2' library making it easy to highlight the first, or last observations, sample minimum and maximum. The goal is to provide additional context. Or just some visual sugar.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
