{% set version = "0.0.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggpointless
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggpointless_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggpointless/ggpointless_{{ version }}.tar.gz
  sha256: 497b8e3c0fca84f25903fcdb9a6de21a31e90a931d7c763f96f54657bf6f8abe

build:
  merge_build_host: true  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggplot2 >=3.3.0
  run:
    - r-base
    - r-ggplot2 >=3.3.0

test:
  commands:
    - $R -e "library('ggpointless')"           # [not win]
    - "\"%R%\" -e \"library('ggpointless')\""  # [win]

about:
  home: https://flrd.github.io/ggpointless/, https://github.com/flrd/ggpointless
  license: MIT
  summary: Add minimal emphasis to your plots. 'ggpointless' is a small extension of the 'ggplot2' library making it easy to highlight the first, or last observations, sample minimum and maximum. The goal is to provide additional context. Or just some visual sugar.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
